name: Update Contributors List

on:
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch:

permissions:
  contents: write

env:
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_contributors_list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set executable permissions for the script
        run: chmod +x ./get-all.sh

      - name: Run the script
        run: |
          ./get-all.sh > result.txt 2>&1
          cat result.txt
          echo "Script exit code: $?"

      - name: Update contributors list
        run: |
          echo "<div align=\"center\">" > result.md
          echo "  <br><img src=\"assets/vanilla-contributors-mono.png?raw=true#gh-dark-mode-only\" height=\"40\">" >> result.md
          echo "  <br><img src=\"assets/vanilla-contributors.png?raw=true#gh-light-mode-only\" height=\"40\">" >> result.md
          echo "---" >> result.md
          echo "  <p>A list of contributors to the project across all repositories</p>" >> result.md
          echo "  <sup>Thanks to everyone in this list who has contributed to our project</sup>" >> result.md
          echo "  <br><sup>We are $(grep -c '* @' result.txt) unique contributors at the moment when this was updated</sup>" >> result.md
          echo "</div>" >> result.md
          echo "" >> result.md
          grep '^\* @' result.txt >> result.md
          echo "" >> result.md
          echo "<div align=\"center\">" >> result.md
          echo "  <sup>This list is updated every week</sup>" >> result.md
          echo "</div>" >> result.md
          mv result.md contributors-list.md
      
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "(chore): Update Contributors List"
          git push

      - name: Display detailed error message
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt
        