name: Run Script and Update Contributors List

on:
  push:
    branches:
      - main

jobs:
  run_script_and_update_contributors_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permissions for the script
        run: chmod +x ./get-all.sh

      - name: Run the script and generate result.txt
        run: |
          ./get-all.sh > result.txt 2>&1
          cat result.txt

      - name: Create result.md file
        run: |
          echo "<div align=\"center\">" > result.md
          echo "  <br><img src=\"assets/vanilla-contributors-mono.png?raw=true#gh-dark-mode-only\" height=\"40\">" >> result.md
          echo "  <br><img src=\"assets/vanilla-contributors.png?raw=true#gh-light-mode-only\" height=\"40\">" >> result.md
          echo "---" >> result.md
          echo "  <p>A list of contributors to the project across all repositories</p>" >> result.md
          echo "  <sup>Thanks to everyone in this list who has contributed to our project</sup>" >> result.md
          echo "  <br><sup>We are $(grep -c '* @' result.txt) unique contributors at the moment when this was updated</sup>" >> result.md
          echo "</div>" >> result.md
          echo "" >> result.md
          grep '* @' result.txt >> result.md
          echo "" >> result.md
          echo "<div align=\"center\">" >> result.md
          echo "  <sup>This list is updated every week</sup>" >> result.md
          echo "</div>" >> result.md

      - name: Replace contributors-list.md with result.md
        run: mv result.md contributors-list.md
